
/* Copyright (c) Sybase, Inc. 2010-2013   All rights reserved.
 
 In addition to the license terms set out in the Sybase License Agreement for
 the Sybase Unwired Platform ("Program"), the following additional or different
 rights and accompanying obligations and restrictions shall apply to the source
 code in this file ("Code").  Sybase grants you a limited, non-exclusive,
 non-transferable, revocable license to use, reproduce, and modify the Code
 solely for purposes of (i) maintaining the Code as reference material to better
 understand the operation of the Program, and (ii) development and testing of
 applications created in connection with your licensed use of the Program.
 The Code may not be transferred, sold, assigned, sublicensed or otherwise
 conveyed (whether by operation of law or otherwise) to another party without
 Sybase's prior written consent.  The following provisions shall apply to any
 modifications you make to the Code: (i) Sybase will not provide any maintenance
 or support for modified Code or problems that result from use of modified Code;
 (ii) Sybase expressly disclaims any warranties and conditions, express or
 implied, relating to modified Code or any problems that result from use of the
 modified Code;OT BE LIABLE FOR ANY LOSS OR DAMAGE RELATING
 TO MODIFICATIONS MADE TO THE CODE OR FOR ANY DAMAGES RESULTING FROM USE OF THE
 MODIFIED CODE, INCLUDING, WITHOUT LIMITATION, ANY INACCURACY OF DATA, LOSS OF
 PROFITS OR DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, EVEN
 IF SYBASE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
 to indemnify, hold harmless, and defend Sybase from and against any claims or
 lawsuits, including attorney's fees, that arise from or are related to the
 modified Code or from use of the modified Code.
 
 */

/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.3.4.285
*/ 

#import "BFSISSubscriptionMetaData.h"

#import "SUPRelationshipMetaData.h"
#import "SUPOperationMetaData.h"
#import "SUPParameterMetaData.h"
#import "SUPIndexMetaData.h"
#import "SUPAttributeMap.h"
#import "SUPOperationMap.h"
#import "SUPClassMap.h"
#import "SUPEntityMap.h"
#import "SUPDataType.h"
#import "BFSISSubscription.h"
#import "SUPObjectList.h"
#import "BFSMP_TesterDBMetaData.h"

@implementation BFSISSubscriptionMetaData

+ (BFSISSubscriptionMetaData*)getInstance
{
    return [[[BFSISSubscriptionMetaData alloc] init] autorelease];
}

- (id)init
{
    if (self = [super init]) {
		self.id = 5;
		self.name = @"SISSubscription";
		self.klass = [BFSISSubscription class];
 		self.allowPending = NO;;

		self.isClientOnly = YES;

		SUPObjectList *attributes = [SUPObjectList getInstance];
		SUPAttributeMetaDataRBS* a_deviceId = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			159:
			[SUPDataType forName:@"string"]:@"varchar(200)":@"deviceId":@"":@"device_id":
			@"":200:0:0:
			@"null":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_deviceId setColumn:@"device_id"];
		SUPAttributeMetaDataRBS* a_username = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			160:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"username":@"":@"user_name":
			@"":100:0:0:
			@"null":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_username setColumn:@"user_name"];
		SUPAttributeMetaDataRBS* a_appname = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			161:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"appname":@"":@"h":
			@"":100:0:0:
			@"sup":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_appname setColumn:@"h"];
		SUPAttributeMetaDataRBS* a_enable = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			162:
			[SUPDataType forName:@"boolean"]:@"tinyint":@"enable":@"":@"i":
			@"":-1:0:0:
			@"false":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_enable setColumn:@"i"];
		SUPAttributeMetaDataRBS* a_adminLock = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			163:
			[SUPDataType forName:@"boolean"]:@"tinyint":@"adminLock":@"":@"admin_lock":
			@"":-1:0:0:
			@"false":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_adminLock setColumn:@"admin_lock"];
		SUPAttributeMetaDataRBS* a_interval = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			164:
			[SUPDataType forName:@"int"]:@"integer":@"interval":@"":@"l":
			@"":-1:0:0:
			@"0":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_interval setColumn:@"l"];
		SUPAttributeMetaDataRBS* a_protocol = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			165:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"protocol":@"":@"m":
			@"":100:0:0:
			@"TCN":NO:@"":
			NO:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_protocol setColumn:@"m"];
		SUPAttributeMetaDataRBS* a_address = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			166:
			[SUPDataType forName:@"string?"]:@"LONG VARCHAR":@"address":@"":@"n":
			@"":-1:0:0:
			@"null":NO:@"":
			NO:NO:YES:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_address setColumn:@"n"];
		SUPAttributeMetaDataRBS* a_domain = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			155:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"domain":@"":@"domain":
			@"":100:0:0:
			@"null":NO:@"":
			YES:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_domain setColumn:@"domain"];
		SUPAttributeMetaDataRBS* a_package = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			156:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"package":@"":@"pkg":
			@"":100:0:0:
			@"null":NO:@"":
			YES:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_package setColumn:@"pkg"];
		SUPAttributeMetaDataRBS* a_syncGroup = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			157:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"syncGroup":@"":@"sync_group":
			@"":100:0:0:
			@"null":NO:@"":
			YES:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_syncGroup setColumn:@"sync_group"];
		SUPAttributeMetaDataRBS* a_clientId = [SUPAttributeMetaDataRBS attributeMetaDataWith:
			158:
			[SUPDataType forName:@"string"]:@"varchar(100)":@"clientId":@"":@"cid":
			@"":100:0:0:
			@"null":NO:@"":
			YES:NO:NO:NO:NO:NO:
			GeneratedScheme_NONE:
			NO:SUPPersonalizationType_None:NO];
		[a_clientId setColumn:@"cid"];
 	
		[attributes addThis:a_deviceId];
		[attributes addThis:a_username];
		[attributes addThis:a_appname];
		[attributes addThis:a_enable];
		[attributes addThis:a_adminLock];
		[attributes addThis:a_interval];
		[attributes addThis:a_protocol];
		[attributes addThis:a_address];
		[attributes addThis:a_domain];
		[attributes addThis:a_package];
		[attributes addThis:a_syncGroup];
		[attributes addThis:a_clientId];
		self.attributes = attributes;
		
		SUPAttributeMap * attributeMap = [SUPAttributeMap getInstance];
   		[attributeMap setAttributes:attributes];
	   	self.attributeMap = attributeMap;

 		SUPOperationMetaData* o_refresh_0 = [SUPOperationMetaData createOperationMetaData:1:(SUPString)@"refresh":[SUPDataType forName:@"void"]:true];
		[o_refresh_0 setIsStatic:NO];
		[o_refresh_0 setIsCreate:NO];
		[o_refresh_0 setIsUpdate:NO];
		[o_refresh_0 setIsDelete:NO]; 		
 		SUPOperationMetaData* o_save_0 = [SUPOperationMetaData createOperationMetaData:2:(SUPString)@"save":[SUPDataType forName:@"void"]:true];
		[o_save_0 setIsStatic:NO];
		[o_save_0 setIsCreate:NO];
		[o_save_0 setIsUpdate:NO];
		[o_save_0 setIsDelete:NO]; 		
 
  		SUPObjectList *operations = [SUPObjectList listWithCapacity:2];
 		[operations addThis:o_refresh_0];
 		[operations addThis:o_save_0];
	 	self.operations = operations;
 	
		SUPOperationMap *operationMap = [SUPOperationMap getInstance];
		[operationMap setOperations:operations];
		self.operationMap = operationMap;		
		self.table = @"sup_sis_subscription";
		self.synchronizationGroup = @"system";

    
			
		[self.keyList add:a_domain];
		[self.keyList add:a_package];
		[self.keyList add:a_syncGroup];
		[self.keyList add:a_clientId];


  self.superClassDefined = YES;
        self.keyClass = @"SISSubscriptionKey";
    }
    return self;
}

@end