
/* Copyright (c) Sybase, Inc. 2010-2013   All rights reserved.
 
 In addition to the license terms set out in the Sybase License Agreement for
 the Sybase Unwired Platform ("Program"), the following additional or different
 rights and accompanying obligations and restrictions shall apply to the source
 code in this file ("Code").  Sybase grants you a limited, non-exclusive,
 non-transferable, revocable license to use, reproduce, and modify the Code
 solely for purposes of (i) maintaining the Code as reference material to better
 understand the operation of the Program, and (ii) development and testing of
 applications created in connection with your licensed use of the Program.
 The Code may not be transferred, sold, assigned, sublicensed or otherwise
 conveyed (whether by operation of law or otherwise) to another party without
 Sybase's prior written consent.  The following provisions shall apply to any
 modifications you make to the Code: (i) Sybase will not provide any maintenance
 or support for modified Code or problems that result from use of modified Code;
 (ii) Sybase expressly disclaims any warranties and conditions, express or
 implied, relating to modified Code or any problems that result from use of the
 modified Code;OT BE LIABLE FOR ANY LOSS OR DAMAGE RELATING
 TO MODIFICATIONS MADE TO THE CODE OR FOR ANY DAMAGES RESULTING FROM USE OF THE
 MODIFIED CODE, INCLUDING, WITHOUT LIMITATION, ANY INACCURACY OF DATA, LOSS OF
 PROFITS OR DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, EVEN
 IF SYBASE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
 to indemnify, hold harmless, and defend Sybase from and against any claims or
 lawsuits, including attorney's fees, that arise from or are related to the
 modified Code or from use of the modified Code.
 
 */

/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.3.4.285
*/ 

#import "BFPersonalizationParameters.h"
#import "BFPersonalizationParameters+Internal.h"
#import "BFPersonalizationParametersMetaData.h"
#import "SUPJsonObject.h"
#import "SUPJsonReader.h"
#import "BFSMP_TesterDB.h"
#import "BFSMP_TesterDB+Internal.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@interface BFPersonalizationParameters(hidden)
-(void)submitPending;
@end
@implementation BFPersonalizationParameters


@synthesize username = _username;
@synthesize usernameUserDefined = _usernameUserDefined;
@synthesize password = _password;
@synthesize passwordUserDefined = _passwordUserDefined;


#pragma mark -
#pragma mark Init, dealloc, getInstance
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[BFPersonalizationParameters metaData];
        [self setClassDelegate:[[self class] delegate]];
        _usernameUserDefined = NO;
        _passwordUserDefined = NO;   
        clientPersonalizationTableName = @"co_smp_tester_1_0_clientpersonalization";
        [self load];
        
    }
    return self;    
}
- (void)dealloc
{
    self.username = nil;
    self.password = nil;
	[super dealloc];
}
+ (BFPersonalizationParameters*)getInstance
{
     BFPersonalizationParameters* me = [[BFPersonalizationParameters alloc] init];
    [me autorelease];
    return me;
}



#pragma mark -
#pragma mark Property getters and setters

- (void)setUsername:(NSString*)newUsername
{
    if (newUsername != self->_username)
    {
        [self->_username release];
        self->_username = [newUsername retain];
		_usernameUserDefined = YES;
    }
    else {
        if ((newUsername == nil) == (self->_username == nil))
        {
            if (_usernameUserDefined == NO)
            {
                _usernameUserDefined = YES;
            }
        }
    }
}
- (void)setUsernameUserDefined:(BOOL)newUsernameUserDefined
{
    if (newUsernameUserDefined != self->_usernameUserDefined)
    {
        self->_usernameUserDefined = newUsernameUserDefined;
    }
}
- (void)setPassword:(NSString*)newPassword
{
    if (newPassword != self->_password)
    {
        [self->_password release];
        self->_password = [newPassword retain];
		_passwordUserDefined = YES;
    }
    else {
        if ((newPassword == nil) == (self->_password == nil))
        {
            if (_passwordUserDefined == NO)
            {
                _passwordUserDefined = YES;
            }
        }
    }
}
- (void)setPasswordUserDefined:(BOOL)newPasswordUserDefined
{
    if (newPasswordUserDefined != self->_passwordUserDefined)
    {
        self->_passwordUserDefined = newPasswordUserDefined;
    }
}

#pragma mark -
#pragma mark Metadata methods

static SUPClassMetaDataRBS* BFPersonalizationParameters_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (BFPersonalizationParameters_META_DATA == nil) {
 	   	BFPersonalizationParameters_META_DATA = [[BFPersonalizationParametersMetaData alloc] init];
	}
	
	return BFPersonalizationParameters_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
#pragma mark -
#pragma mark Attribute get/set methods (internal)
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 259:
        return self.username;
    case 261:
        return self.password;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_ :(SUPString)v
{
    switch(id_)
    {
    case 259:
        self.username = v;
        break;;
    case 261:
        self.password = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
-(SUPBoolean) getAttributeBoolean:(int)id_
{
    switch(id_)
    {
    case 260:
        return self.usernameUserDefined;
    case 262:
        return self.passwordUserDefined;
    default:
        return [super getAttributeBoolean:id_];
    }
}

-(void) setAttributeBoolean:(int)id_ :(SUPBoolean)v
{
    switch(id_)
    {
    case 260:
        self.usernameUserDefined = v;
        break;;
    case 262:
        self.passwordUserDefined = v;
        break;;
    default:
        [super setAttributeBoolean:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_ :(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

#pragma mark -
#pragma mark Delegate method (internal)

static SUPClassDelegate *g_BFPersonalizationParameters_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_BFPersonalizationParameters_delegate == nil) {
			g_BFPersonalizationParameters_delegate = [[SUPClassDelegate alloc] initWithName:@"BFPersonalizationParameters" clazz:[self class]
				metaData:[self metaData] dbDelegate:[BFSMP_TesterDB delegate] database:[BFSMP_TesterDB instance]];
		}
	}
	
	return [[g_BFPersonalizationParameters_delegate retain] autorelease];
}

#pragma mark -
#pragma mark toString method

- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	PersonalizationParameters = \n\
	    username = %@,\n\
	    usernameUserDefined = %i,\n\
	    password = %@,\n\
	    passwordUserDefined = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.username
    	,self.usernameUserDefined
    	,self.password
    	,self.passwordUserDefined
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}

#pragma mark -
#pragma mark JSON methods (internal)



- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_ :(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray
{
    if(jsonArray == nil)
        return nil;
    
    SUPObjectList* instanceList = [[SUPObjectList alloc] initWithCapacity:1];
    [instanceList autorelease];
    if(instanceList == nil)
        return nil;

    for (SUPJsonObject* jsonObject in jsonArray)
    {
        BFPersonalizationParameters* inst = [[BFPersonalizationParameters alloc] init];
        [inst readJson:jsonObject];
        [instanceList add:inst];
        [inst release];
    }
    return instanceList;
}

+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList
{
    SUPJsonArray* jsonArray = [[SUPJsonArray alloc] init];
    [jsonArray autorelease];
    for (BFPersonalizationParameters* inst in instanceList)
    {
        SUPJsonObject *o = [[SUPJsonObject alloc] init];
        [inst writeJson:o];
        [jsonArray add:o];
        [o release];
    }
    return jsonArray;
}

@end